version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    ports:
      - "80:80"
    environment:
      - AWS_REGION=eu-west-1
      - DYNAMODB_ENDPOINT=http://dynamodb:8000
    env_file:
      - ./docker/.env
    depends_on:
      - dynamodb

  dynamodb:
    image: amazon/dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - dynamodb-data:/data

volumes:
  dynamodb-data:
